export default [
    {_id: 'themes:1', igdbId: '1', name: 'Action', type: 'themes'},
    {_id: 'themes:17', igdbId: '17', name: 'Fantasy', type: 'themes'},
    {_id: 'themes:18', igdbId: '18', name: 'Science fiction', type: 'themes'},
    {_id: 'themes:21', igdbId: '21', name: 'Survival', type: 'themes'},
    {_id: 'themes:33', igdbId: '33', name: 'Sandbox', type: 'themes'},
    {_id: 'game_modes:1', igdbId: '1', name: 'Single player', type: 'game_modes'},
    {_id: 'game_modes:2', igdbId: '2', name: 'Multiplayer', type: 'game_modes'},
    {_id: 'genres:4', igdbId: '4', name: 'Fighting', type: 'genres'},
    {_id: 'genres:12', igdbId: '12', name: 'Role-playing (RPG)', type: 'genres'},
    {_id: 'genres:31', igdbId: '31', name: 'Adventure', type: 'genres'},
    {_id: 'game_engines:212', igdbId: '212', name: 'Luminous Studio', type: 'game_engines'},
    {_id: 'player_perspectives:2', igdbId: '2', name: 'Third person', type: 'player_perspectives'},
    {_id: 'platforms:48', igdbId: '48', name: 'PlayStation 4', type: 'platforms'},
    {_id: 'platforms:49', igdbId: '49', name: 'Xbox One', type: 'platforms'},
    {_id: 'collection:39', igdbId: '39', name: 'Final Fantasy', type: 'collection'},
    {_id: 'themes:27', igdbId: '27', name: 'Comedy', type: 'themes'},
    {_id: 'themes:38', igdbId: '38', name: 'Open world', type: 'themes'},
    {_id: 'genres:5', igdbId: '5', name: 'Shooter', type: 'genres'},
    {_id: 'genres:10', igdbId: '10', name: 'Racing', type: 'genres'},
    {_id: 'genres:14', igdbId: '14', name: 'Sport', type: 'genres'},
    {_id: 'game_engines:26', igdbId: '26', name: 'RAGE', type: 'game_engines'},
    {_id: 'player_perspectives:1', igdbId: '1', name: 'First person', type: 'player_perspectives'},
    {_id: 'platforms:6', igdbId: '6', name: 'PC (Microsoft Windows)', type: 'platforms'},
    {_id: 'platforms:9', igdbId: '9', name: 'PlayStation 3', type: 'platforms'},
    {_id: 'platforms:12', igdbId: '12', name: 'Xbox 360', type: 'platforms'},
    {_id: 'collection:130', igdbId: '130', name: 'GTA', type: 'collection'},
    {_id: 'game_engines:24', igdbId: '24', name: 'REDengine', type: 'game_engines'},
    {_id: 'collection:62', igdbId: '62', name: 'The Witcher', type: 'collection'},
    {_id: 'game_engines:17', igdbId: '17', name: 'Havok Physics', type: 'game_engines'},
    {_id: 'game_engines:95', igdbId: '95', name: 'Creation Engine', type: 'game_engines'},
    {_id: 'collection:6', igdbId: '6', name: 'The Elder Scrolls', type: 'collection'},
    {_id: 'themes:32', igdbId: '32', name: 'Non-fiction', type: 'themes'},
    {_id: 'game_engines:41', igdbId: '41', name: 'RenderWare', type: 'game_engines'},
    {_id: 'platforms:8', igdbId: '8', name: 'PlayStation 2', type: 'platforms'},
    {_id: 'platforms:11', igdbId: '11', name: 'Xbox', type: 'platforms'},
    {_id: 'platforms:14', igdbId: '14', name: 'Mac', type: 'platforms'},
    {_id: 'platforms:34', igdbId: '34', name: 'Android', type: 'platforms'},
    {_id: 'platforms:36', igdbId: '36', name: 'Xbox Live Arcade', type: 'platforms'},
    {_id: 'platforms:39', igdbId: '39', name: 'iOS', type: 'platforms'},
    {_id: 'game_modes:3', igdbId: '3', name: 'Co-operative', type: 'game_modes'},
    {_id: 'game_modes:4', igdbId: '4', name: 'Split screen', type: 'game_modes'},
    {_id: 'genres:8', igdbId: '8', name: 'Platform', type: 'genres'},
    {_id: 'genres:9', igdbId: '9', name: 'Puzzle', type: 'genres'},
    {_id: 'game_engines:3', igdbId: '3', name: 'Source', type: 'game_engines'},
    {_id: 'platforms:3', igdbId: '3', name: 'Linux', type: 'platforms'},
    {_id: 'collection:87', igdbId: '87', name: 'Portal', type: 'collection'},
    {_id: 'themes:19', igdbId: '19', name: 'Horror', type: 'themes'},
    {_id: 'collection:35', igdbId: '35', name: 'Half-Life', type: 'collection'},
    {_id: 'platforms:167', igdbId: '167', name: 'PlayStation 5', type: 'platforms'},
    {_id: 'platforms:169', igdbId: '169', name: 'Xbox Series', type: 'platforms'},
    {_id: 'platforms:170', igdbId: '170', name: 'Google Stadia', type: 'platforms'},
    {_id: 'themes:23', igdbId: '23', name: 'Stealth', type: 'themes'},
    {_id: 'collection:864', igdbId: '864', name: 'The Last of Us', type: 'collection'},
    {_id: 'genres:13', igdbId: '13', name: 'Simulator', type: 'genres'},
    {_id: 'game_engines:351', igdbId: '351', name: 'Unreal Engine 3', type: 'game_engines'},
    {_id: 'collection:25', igdbId: '25', name: 'Mass Effect', type: 'collection'},
    {_id: 'themes:20', igdbId: '20', name: 'Thriller', type: 'themes'},
    {_id: 'themes:39', igdbId: '39', name: 'Warfare', type: 'themes'},
    {_id: 'game_engines:4', igdbId: '4', name: 'GoldSrc', type: 'game_engines'},
    {_id: 'themes:22', igdbId: '22', name: 'Historical', type: 'themes'},
    {_id: 'game_engines:8', igdbId: '8', name: 'Havok', type: 'game_engines'},
    {_id: 'game_engines:9', igdbId: '9', name: 'Anvil', type: 'game_engines'},
    {_id: 'collection:18', igdbId: '18', name: 'Assassin\u0027s Creed', type: 'collection'},
    {_id: 'genres:33', igdbId: '33', name: 'Arcade', type: 'genres'},
    {_id: 'collection:2100', igdbId: '2100', name: 'Red Dead Redemption', type: 'collection'},
    {_id: 'game_engines:412', igdbId: '412', name: 'Decima', type: 'game_engines'},
    {_id: 'collection:6304', igdbId: '6304', name: 'Horizon', type: 'collection'},
    {_id: 'collection:97', igdbId: '97', name: 'Uncharted', type: 'collection'},
    {_id: 'game_engines:16', igdbId: '16', name: 'Disrupt', type: 'game_engines'},
    {_id: 'collection:2173', igdbId: '2173', name: 'Watch Dogs', type: 'collection'},
    {_id: 'themes:31', igdbId: '31', name: 'Drama', type: 'themes'},
    {_id: 'game_engines:6', igdbId: '6', name: 'Unreal Engine', type: 'game_engines'},
    {_id: 'collection:2724', igdbId: '2724', name: 'Life is Strange', type: 'collection'},
    {_id: 'collection:3', igdbId: '3', name: 'Fallout', type: 'collection'},
    {_id: 'platforms:46', igdbId: '46', name: 'PlayStation Vita', type: 'platforms'},
    {_id: 'collection:225', igdbId: '225', name: 'Borderlands', type: 'collection'},
    {_id: 'game_modes:5', igdbId: '5', name: 'Massively Multiplayer Online (MMO)', type: 'game_modes'},
    {_id: 'genres:24', igdbId: '24', name: 'Tactical', type: 'genres'},
    {_id: 'game_engines:433', igdbId: '433', name: 'In House Engine', type: 'game_engines'},
    {_id: 'platforms:203', igdbId: '203', name: 'Stadia', type: 'platforms'},
    {_id: 'collection:2406', igdbId: '2406', name: 'Destiny', type: 'collection'},
    {_id: 'game_engines:10', igdbId: '10', name: 'AnvilNext', type: 'game_engines'},
    {_id: 'player_perspectives:3', igdbId: '3', name: 'Bird view / Isometric', type: 'player_perspectives'},
    {_id: 'platforms:7', igdbId: '7', name: 'PlayStation', type: 'platforms'},
    {_id: 'platforms:45', igdbId: '45', name: 'PlayStation Network', type: 'platforms'},
    {_id: 'platforms:130', igdbId: '130', name: 'Nintendo Switch', type: 'platforms'},
    {_id: 'collection:2807', igdbId: '2807', name: 'Final Fantasy VII', type: 'collection'},
    {_id: 'genres:25', igdbId: '25', name: 'Hack and slash/Beat \u0027em up', type: 'genres'},
    {_id: 'game_engines:61', igdbId: '61', name: 'LithTech', type: 'game_engines'},
    {_id: 'collection:2624', igdbId: '2624', name: 'Middle-earth', type: 'collection'},
    {_id: 'game_engines:67', igdbId: '67', name: 'MAX-FX', type: 'game_engines'},
    {_id: 'collection:81', igdbId: '81', name: 'Max Payne', type: 'collection'},
    {_id: 'game_engines:72', igdbId: '72', name: 'Odyssey', type: 'game_engines'},
    {_id: 'collection:23', igdbId: '23', name: 'Star Wars: Knights of the Old Republic', type: 'collection'},
    {_id: 'platforms:5', igdbId: '5', name: 'Wii', type: 'platforms'},
    {
        _id: 'platforms:19',
        igdbId: '19',
        name: 'Super Nintendo Entertainment System (SNES)',
        type: 'platforms',
    },
    {_id: 'platforms:20', igdbId: '20', name: 'Nintendo DS', type: 'platforms'},
    {_id: 'platforms:58', igdbId: '58', name: 'Super Famicom', type: 'platforms'},
    {_id: 'collection:345', igdbId: '345', name: 'Chrono', type: 'collection'},
    {_id: 'genres:15', igdbId: '15', name: 'Strategy', type: 'genres'},
    {_id: 'genres:32', igdbId: '32', name: 'Indie', type: 'genres'},
    {_id: 'collection:5687', igdbId: '5687', name: 'Hello Neighbor', type: 'collection'},
    {_id: 'game_engines:79', igdbId: '79', name: 'GameMaker: Studio', type: 'game_engines'},
    {_id: 'collection:430', igdbId: '430', name: 'Hotline Miami', type: 'collection'},
    {_id: 'collection:1', igdbId: '1', name: 'Bioshock', type: 'collection'},
    {_id: 'genres:2', igdbId: '2', name: 'Point-and-click', type: 'genres'},
    {_id: 'game_engines:12', igdbId: '12', name: 'Telltale Tool', type: 'game_engines'},
    {
        _id: 'collection:564',
        igdbId: '564',
        name: 'The Walking Dead - A Telltale Games Series',
        type: 'collection',
    },
    {_id: 'themes:43', igdbId: '43', name: 'Mystery', type: 'themes'},
    {_id: 'collection:2824', igdbId: '2824', name: 'The Wolf Among Us', type: 'collection'},
    {_id: 'themes:28', igdbId: '28', name: 'Business', type: 'themes'},
    {_id: 'game_engines:103', igdbId: '103', name: 'Microsoft XNA', type: 'game_engines'},
    {_id: 'genres:16', igdbId: '16', name: 'Turn-based strategy (TBS)', type: 'genres'},
    {_id: 'genres:35', igdbId: '35', name: 'Card \u0026 Board Game', type: 'genres'},
    {_id: 'game_engines:13', igdbId: '13', name: 'Unity', type: 'game_engines'},
    {_id: 'player_perspectives:5', igdbId: '5', name: 'Text', type: 'player_perspectives'},
    {_id: 'collection:2342', igdbId: '2342', name: 'Hearthstone', type: 'collection'},
    {_id: 'player_perspectives:4', igdbId: '4', name: 'Side view', type: 'player_perspectives'},
    {_id: 'platforms:24', igdbId: '24', name: 'Game Boy Advance', type: 'platforms'},
    {_id: 'platforms:47', igdbId: '47', name: 'Virtual Console (Nintendo)', type: 'platforms'},
    {_id: 'platforms:74', igdbId: '74', name: 'Windows Phone', type: 'platforms'},
    {_id: 'game_engines:104', igdbId: '104', name: 'MonoGame', type: 'game_engines'},
    {_id: 'game_engines:476', igdbId: '476', name: 'OpenFL', type: 'game_engines'},
    {_id: 'game_engines:14', igdbId: '14', name: 'MT Framework', type: 'game_engines'},
    {_id: 'collection:17', igdbId: '17', name: 'Devil May Cry', type: 'collection'},
    {_id: 'game_engines:610', igdbId: '610', name: 'Heaps.io', type: 'game_engines'},
    {_id: 'collection:1114', igdbId: '1114', name: 'The Banner Saga', type: 'collection'},
    {_id: 'collection:4243', igdbId: '4243', name: 'Reigns', type: 'collection'},
    {_id: 'platforms:38', igdbId: '38', name: 'PlayStation Portable', type: 'platforms'},
    {_id: 'collection:2105', igdbId: '2105', name: 'Final Fantasy Tactics', type: 'collection'},
    {_id: 'themes:41', igdbId: '41', name: '4X (explore, expand, exploit, and exterminate)', type: 'themes'},
    {_id: 'game_engines:490', igdbId: '490', name: 'Bedrock Engine', type: 'game_engines'},
    {_id: 'player_perspectives:7', igdbId: '7', name: 'Virtual Reality', type: 'player_perspectives'},
    {_id: 'platforms:132', igdbId: '132', name: 'Amazon Fire TV', type: 'platforms'},
    {_id: 'collection:1130', igdbId: '1130', name: 'Minecraft', type: 'collection'},
    {_id: 'collection:6220', igdbId: '6220', name: 'Harvest Moon (new)', type: 'collection'},
    {_id: 'genres:11', igdbId: '11', name: 'Real Time Strategy (RTS)', type: 'genres'},
    {_id: 'collection:2152', igdbId: '2152', name: 'Majesty', type: 'collection'},
    {_id: 'game_engines:532', igdbId: '532', name: 'GameMaker Studio 2', type: 'game_engines'},
    {_id: 'collection:1502', igdbId: '1502', name: 'Harry Potter', type: 'collection'},
    {_id: 'collection:2911', igdbId: '2911', name: 'Sonny', type: 'collection'},
    {_id: 'game_engines:54', igdbId: '54', name: 'Gamebryo', type: 'game_engines'},
    {_id: 'platforms:41', igdbId: '41', name: 'Wii U', type: 'platforms'},
    {_id: 'game_engines:19', igdbId: '19', name: 'Snowdrop', type: 'game_engines'},
    {_id: 'collection:5402', igdbId: '5402', name: 'The Division', type: 'collection'},
    {_id: 'game_engines:7', igdbId: '7', name: 'Scimitar', type: 'game_engines'},
    {_id: 'collection:240', igdbId: '240', name: 'Super Mario', type: 'collection'},
    {_id: 'game_modes:6', igdbId: '6', name: 'Battle Royale', type: 'game_modes'},
    {_id: 'game_engines:439', igdbId: '439', name: 'Unreal Engine 4', type: 'game_engines'},
    {_id: 'collection:197', igdbId: '197', name: 'Saints Row', type: 'collection'},
    {_id: 'platforms:37', igdbId: '37', name: 'Nintendo 3DS', type: 'platforms'},
    {_id: 'collection:555', igdbId: '555', name: 'Terraria', type: 'collection'},
    {_id: 'platforms:21', igdbId: '21', name: 'Nintendo GameCube', type: 'platforms'},
    {_id: 'platforms:56', igdbId: '56', name: 'WiiWare', type: 'platforms'},
    {_id: 'platforms:18', igdbId: '18', name: 'Nintendo Entertainment System (NES)', type: 'platforms'},
    {_id: 'platforms:51', igdbId: '51', name: 'Family Computer Disk System', type: 'platforms'},
    {_id: 'collection:106', igdbId: '106', name: 'The Legend of Zelda', type: 'collection'},
    {_id: 'game_engines:217', igdbId: '217', name: 'Lightweight Java Game Library', type: 'game_engines'},
    {_id: 'game_engines:42', igdbId: '42', name: 'SpeedTree', type: 'game_engines'},
    {_id: 'collection:543', igdbId: '543', name: 'Dark Souls', type: 'collection'},
    {_id: 'game_engines:55', igdbId: '55', name: 'Euphoria Engine', type: 'game_engines'},
    {_id: 'collection:366', igdbId: '366', name: 'Red Dead', type: 'collection'},
    {_id: 'collection:697', igdbId: '697', name: 'Midnight Club', type: 'collection'},
    {_id: 'platforms:137', igdbId: '137', name: 'New Nintendo 3DS', type: 'platforms'},
    {_id: 'platforms:306', igdbId: '306', name: 'Satellaview', type: 'platforms'},
    {_id: 'platforms:307', igdbId: '307', name: 'Game \u0026 Watch', type: 'platforms'},
    {_id: 'collection:6118', igdbId: '6118', name: 'Super Mario Bros.', type: 'collection'},
    {_id: 'game_engines:116', igdbId: '116', name: 'id Tech 1', type: 'game_engines'},
    {_id: 'platforms:13', igdbId: '13', name: 'PC DOS', type: 'platforms'},
    {_id: 'platforms:30', igdbId: '30', name: 'Sega 32X', type: 'platforms'},
    {_id: 'platforms:32', igdbId: '32', name: 'Sega Saturn', type: 'platforms'},
    {_id: 'platforms:50', igdbId: '50', name: '3DO Interactive Multiplayer', type: 'platforms'},
    {_id: 'platforms:62', igdbId: '62', name: 'Atari Jaguar', type: 'platforms'},
    {_id: 'collection:129', igdbId: '129', name: 'Doom', type: 'collection'},
    {_id: 'game_engines:287', igdbId: '287', name: 'EAGL', type: 'game_engines'},
    {_id: 'collection:12', igdbId: '12', name: 'Need for Speed', type: 'collection'},
    {_id: 'game_engines:76', igdbId: '76', name: 'Jade', type: 'game_engines'},
    {_id: 'collection:187', igdbId: '187', name: 'Prince of Persia', type: 'collection'},
    {_id: 'platforms:44', igdbId: '44', name: 'Tapwave Zodiac', type: 'platforms'},
    {_id: 'collection:571', igdbId: '571', name: 'Mother', type: 'collection'},
    {_id: 'collection:428', igdbId: '428', name: 'Mirror\u0027s Edge', type: 'collection'},
    {_id: 'themes:35', igdbId: '35', name: 'Kids', type: 'themes'},
    {_id: 'game_engines:136', igdbId: '136', name: 'Popcap Games Framework', type: 'game_engines'},
    {_id: 'platforms:159', igdbId: '159', name: 'Nintendo DSi', type: 'platforms'},
    {_id: 'collection:572', igdbId: '572', name: 'Plants vs. Zombies', type: 'collection'},
    {_id: 'platforms:73', igdbId: '73', name: 'BlackBerry OS', type: 'platforms'},
    {_id: 'collection:891', igdbId: '891', name: 'Asphalt', type: 'collection'},
    {_id: 'collection:3000', igdbId: '3000', name: 'Monument Valley', type: 'collection'},
    {_id: 'game_engines:156', igdbId: '156', name: 'Clickteam Fusion', type: 'game_engines'},
    {_id: 'collection:1150', igdbId: '1150', name: 'Five Nights at Freddy\u0027s', type: 'collection'},
    {_id: 'collection:183', igdbId: '183', name: 'Tomb Raider', type: 'collection'},
    {_id: 'platforms:15', igdbId: '15', name: 'Commodore C64/128', type: 'platforms'},
    {_id: 'platforms:26', igdbId: '26', name: 'ZX Spectrum', type: 'platforms'},
    {_id: 'platforms:27', igdbId: '27', name: 'MSX', type: 'platforms'},
    {_id: 'platforms:33', igdbId: '33', name: 'Game Boy', type: 'platforms'},
    {_id: 'platforms:35', igdbId: '35', name: 'Sega Game Gear', type: 'platforms'},
    {_id: 'platforms:52', igdbId: '52', name: 'Arcade', type: 'platforms'},
    {_id: 'platforms:55', igdbId: '55', name: 'Mobile', type: 'platforms'},
    {_id: 'platforms:65', igdbId: '65', name: 'Atari 8-bit', type: 'platforms'},
    {_id: 'platforms:66', igdbId: '66', name: 'Atari 5200', type: 'platforms'},
    {_id: 'platforms:67', igdbId: '67', name: 'Intellivision', type: 'platforms'},
    {_id: 'platforms:71', igdbId: '71', name: 'Commodore VIC-20', type: 'platforms'},
    {_id: 'platforms:75', igdbId: '75', name: 'Apple II', type: 'platforms'},
    {_id: 'platforms:77', igdbId: '77', name: 'Sharp X1', type: 'platforms'},
    {_id: 'platforms:120', igdbId: '120', name: 'Neo Geo Pocket Color', type: 'platforms'},
    {_id: 'platforms:125', igdbId: '125', name: 'PC-8801', type: 'platforms'},
    {_id: 'platforms:127', igdbId: '127', name: 'Fairchild Channel F', type: 'platforms'},
    {_id: 'platforms:129', igdbId: '129', name: 'Texas Instruments TI-99', type: 'platforms'},
    {_id: 'platforms:149', igdbId: '149', name: 'PC-98', type: 'platforms'},
    {_id: 'platforms:152', igdbId: '152', name: 'FM-7', type: 'platforms'},
    {_id: 'platforms:157', igdbId: '157', name: 'NEC PC-6000 Series', type: 'platforms'},
    {_id: 'collection:526', igdbId: '526', name: 'Pacman', type: 'collection'},
    {_id: 'collection:1244', igdbId: '1244', name: 'Sid Meier\u0027s Pirates!', type: 'collection'},
    {_id: 'platforms:16', igdbId: '16', name: 'Amiga', type: 'platforms'},
    {_id: 'platforms:29', igdbId: '29', name: 'Sega Mega Drive/Genesis', type: 'platforms'},
    {_id: 'platforms:63', igdbId: '63', name: 'Atari ST/STE', type: 'platforms'},
    {_id: 'platforms:115', igdbId: '115', name: 'Apple IIGS', type: 'platforms'},
    {_id: 'collection:1806', igdbId: '1806', name: 'Another World', type: 'collection'},
    {_id: 'genres:34', igdbId: '34', name: 'Visual Novel', type: 'genres'},
    {_id: 'game_engines:64', igdbId: '64', name: 'Adobe Flash Player', type: 'game_engines'},
    {_id: 'platforms:82', igdbId: '82', name: 'Web browser', type: 'platforms'},
    {_id: 'themes:40', igdbId: '40', name: 'Party', type: 'themes'},
    {_id: 'platforms:4', igdbId: '4', name: 'Nintendo 64', type: 'platforms'},
    {_id: 'collection:453', igdbId: '453', name: 'Mario Party', type: 'collection'},
    {_id: 'collection:1979', igdbId: '1979', name: 'Clash of Clans', type: 'collection'},
    {_id: 'platforms:22', igdbId: '22', name: 'Game Boy Color', type: 'platforms'},
    {_id: 'collection:1569', igdbId: '1569', name: 'Pokémon Trading Card Game', type: 'collection'},
    {_id: 'game_engines:52', igdbId: '52', name: 'In-house engine', type: 'game_engines'},
];
